pull ucsd majors for autocomplete
acmucsd/membership-portal-ui pull request #363
Opened 2020-09-28 20:54 UTC by StoneT2000

<img width="657" alt="Screen Shot 2020-09-28 at 1 53 09 PM" src="https://user-images.githubusercontent.com/35373228/94484990-1a1ea100-0192-11eb-98ab-b779ff5bd868.png">
major change is making major field longer for majors with longer names

custom major names are not possible anymore

2020-09-30 10:32 UTC, leestanley commented
![image](https://user-images.githubusercontent.com/8893880/94674706-73d7b600-02cd-11eb-8f88-1a5ebdcdbeea.png)
The div isn't tall enough on my screen to fit the ACM logo and has very little padding on the `Already have an account? Sign in.`

2020-09-30 10:33 UTC, leestanley requested changes

2020-09-30 10:33 UTC, leestanley commented on src/components/RegisterForm/majors.json
> +  "majors": ["Anthropology","Biological Anthropology","Bioengineering","Bioengineering (Bioinformatics)","Bioengineering: BioSystems","Bioengineering (Biotechnology)","Biology with Specialization in
Can we do some more condensing here by moving all the specializations of `International Studies: xyz` to just `International Studies`. Same with Undeclared/Bioengineering

2020-09-30 10:34 UTC, leestanley commented
Not part of this PR but not sure why the year defaults to `0` here 👀 
![image](https://user-images.githubusercontent.com/8893880/94674969-d5982000-02cd-11eb-8f43-9d7f0d324b92.png)

2020-09-30 16:43 UTC, steets250 commented
It defaults to 0 cause the default value of that field isn't set. If we assign the first year in the array, then the drop down will work correctly. Idk if you want to include that in this PR, but it's like a 1-2 line fix.

2020-12-18 01:12 UTC, steets250 commented
Brushing the dust off this one... can you add a hint to the field so it says "Major" before a major is selected, and then switch the major field to being a full width field? It was fine with the old design but the redesign shrunk the width of the field and now the names get cut off:

<img width="365" alt="Screen Shot 2020-12-17 at 5 11 23 PM" src="https://user-images.githubusercontent.com/5706163/102561968-e5ccc980-408a-11eb-9302-f649b39fd64d.png">

2021-01-23 00:08 UTC, seanye24 commented
Moved year field to new line, added major placeholder
#363

2021-01-25 08:28 UTC, steets250 approved these changes
@seanye24  looks good! You can go ahead and merge.

2021-01-26 00:14 UTC, merged