Resume upload user side
acmucsd/membership-portal-ui pull request #599
Opened 2023-01-17 03:32 UTC by raymosun

Work in progress PR. Resume upload user side is basically done, but not fully tested. Also might want to change how updating resume visibility works.

![image](https://user-images.githubusercontent.com/30709485/212803845-6c6618f0-d51a-475d-8e48-3beeff4c6ae7.png)
![image](https://user-images.githubusercontent.com/30709485/212803983-23b57a15-a868-474c-9193-8db49387d71f.png)
![image](https://user-images.githubusercontent.com/30709485/212803959-2d8adcae-726e-4c55-9ac1-7424603c3f9e.png)

2023-01-27 03:41 UTC, farisashai requested changes
I know this is still in progress but I'm going to leave some nitpicks on functionality from demoing the page and future TODOs to be aware of.

**1. "Resume not visible to recruiters" doesn't make sense to show if there's no resume.**

![Screenshot 2023-01-26 at 7 30 44 PM](https://user-images.githubusercontent.com/33165426/215004005-dd2c4d74-1a93-47d0-951e-85a79c7cd140.jpg)

**2. The toggle input doesn't have enough space between the file upload above or between the switch and the text. Try to play around with this and see if we can make it look a bit better and maybe more consistent with other spacing values on the page.**

![Screenshot 2023-01-26 at 7 32 02 PM](https://user-images.githubusercontent.com/33165426/215004124-489b212f-8142-408e-acda-65b9b9bd345f.jpg)

3. We still need to fix the visibility body field on the initial POST request from the new backend change.
![Screenshot 2023-01-26 at 7 40 17 PM](https://user-images.githubusercontent.com/33165426/215004899-ed0ae360-b1d4-4eac-92b1-ca548cbb75d2.jpg)

2023-02-09 21:19 UTC, trevorkw7 commented on src/profile/components/ManageResume/index.tsx
> +  const uploadIcon = (
Might want to try putting these in assets and import them as React Components

2023-02-09 21:24 UTC, trevorkw7 commented
Everything else looks good to me in terms of functionality. The only behavior I saw during my testing that might need to be changed is how the spinning indicator for an upload continues to spin infinitely even after we get a status 500 error and toast message for a file being too large. 
<img width="788" alt="Screen Shot 2023-02-09 at 1 13 55 PM" src="https://user-images.githubusercontent.com/54345106/217942421-e8288c83-25bc-476c-9331-04a9f43bdd4a.png">

2023-02-10 11:47 UTC, raymosun commented
> Everything else looks good to me in terms of functionality. The only behavior I saw during my testing that might need to be changed is how the spinning indicator for an upload continues to spin infinitely even after we get a status 500 error and toast message for a file being too large. <img alt="Screen Shot 2023-02-09 at 1 13 55 PM" width="788" src="https://user-images.githubusercontent.com/54345106/217942421-e8288c83-25bc-476c-9331-04a9f43bdd4a.png">

Fixed the points you brought up in latest commits, thanks!

2023-02-10 21:26 UTC, farisashai approved these changes

2023-02-11 00:12 UTC, merged