Functional admin-side user resume table
acmucsd/membership-portal-ui pull request #601
Opened 2023-01-27 03:48 UTC by trevorkw7

Admin-side user resume table is functional but needs some type definition and css cleanup work.

2023-02-03 10:19 UTC, raymosun requested changes
Looks really good! Just noticed some minor things.

2023-02-03 10:19 UTC, raymosun commented on src/admin/components/UserResumeTable/index.tsx
> +  const handleDonwloadZip = () => {
Looks like download is misspelled here

2023-02-03 10:19 UTC, raymosun commented on src/admin/components/UserResumeTable/index.tsx
> +        )}
To achieve this, you could have one button with `disabled={selectedRowKeys.length < 1}` (stole this idea from store code 😉 )

2023-02-10 21:34 UTC, farisashai approved these changes
Looks good to merge once we fix Raymond's comments 🚀

2023-02-11 00:30 UTC, raymosun approved these changes
Noice

2023-02-11 00:40 UTC, merged